### PR TITLE
Optimised Dockerfile build

### PR DESCRIPTION
**Pull request by hebbo**
## Approvals

- [x] Verified
- [ ] Tim
- [x] Larry

Introduced the optimisation described here:
https://www.datawire.io/not-engineer-running-3-5gb-docker-images/

The results? Well... not a massive improvement but at least we know it is optimal now (unless I missed something)

```
local/docker-ansible        latest              0058e745943f        13 minutes ago      437.6 MB  <-- OPTIMISED
cultureamp/docker-ansible   latest              c093c6052e55        29 hours ago        441.4 MB  <-- OLD
```

### CODE REVIEW

**Comment by hebbo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TE2VTvIc&#x2F;301-optimise-culture-docker-ansible-docker-image-build"> Optimise culture&#x2F;docker-ansible Docker image build</a>

**Comment by ptolemy428** [comment]
looks good to me.

**Comment by TimMoore** [comment]
I just tried following the steps from the [blog post](https://www.datawire.io/not-engineer-running-3-5gb-docker-images/) and it seems that even after running `apt-get clean` it still leaves behind a lot of stuff in `/var/lib/apt`, so maybe it is worth explicitly running `rm -rf /var/lib/apt` as the post suggests.

**Comment by hebbo** [comment]
Not very clear to me whether removing the contents of /var/lib/apt actually
adds any value on top of running apt-get clean.

If you look at the first comment the author clarifies that using the clean
command has the same effect. He just used rm to be more explicit.

I will try to delete the contents of /var/lib/apt anyway and compare the
results.

**Comment by TimMoore** [comment]
I think that commenter was incorrect. `apt-get clean` doesn't remove everything in `/var/lib/apt`

I found this Debian bug report, which is pretty old, but appears to still be true https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762891

I'm trying it out now... I'll let you know how much difference it makes.

**Comment by TimMoore** [comment]
It makes a bit of difference, but still not huge. `e14d7864b4db` is the same as `cultureamp/docker-ansible` but with an extra remove at the end:

```diff
diff --git a/Dockerfile b/Dockerfile
index d2b4d14..5ee53ee 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,7 +10,8 @@ RUN apt-get update \
                                       python-pip \
                                       curl \
     && apt-get clean \
-    && apt-get autoremove
+    && apt-get autoremove \
+    && rm -rf /var/lib/apt
 
 RUN pip install boto \
                 awscli
```

It saves 21.8 extra MB

```
[19:04:07] tim@Tim-Culture-Amp:~/src/docker-ansible (master *=) $ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
<none>                          <none>              e14d7864b4db        10 seconds ago      415.8 MB
<none>                          <none>              423fe49a2fee        8 minutes ago       437.6 MB
cultureamp/docker-ansible       latest              1903dd0f3c9a        59 minutes ago      437.6 MB
ptolemy428/docker-troposphere   latest              427d75b4a7b8        10 days ago         678.7 MB
cultureamp/docker-python        latest              7a0969482ad4        3 weeks ago         519.6 MB
ubuntu                          14.04               90d5884b1ee0        3 weeks ago         188 MB
<none>                          <none>              52ef7e449605        5 weeks ago         423.7 MB

[19:04:18] tim@Tim-Culture-Amp:~/src/docker-ansible (master *=) $ docker history cultureamp/docker-ansible
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
1903dd0f3c9a        59 minutes ago      /bin/sh -c pip install boto                 a   33.67 MB            
<missing>           About an hour ago   /bin/sh -c apt-get update     && apt-get -y -   215.9 MB            
<missing>           About an hour ago   /bin/sh -c echo "deb-src http://ppa.launchpad   2.027 kB            
<missing>           About an hour ago   /bin/sh -c echo "deb http://ppa.launchpad.net   1.959 kB            
<missing>           About an hour ago   /bin/sh -c #(nop) MAINTAINER Larry Liang <lar   0 B                 
<missing>           3 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           3 weeks ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
<missing>           3 weeks ago         /bin/sh -c rm -rf /var/lib/apt/lists/*          0 B                 
<missing>           3 weeks ago         /bin/sh -c set -xe   && echo '#!/bin/sh' > /u   194.5 kB            
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:b64f702c5b33d12426   187.8 MB            

[19:04:45] tim@Tim-Culture-Amp:~/src/docker-ansible (master *=) $ docker history e14d7864b4db
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
e14d7864b4db        43 seconds ago       /bin/sh -c pip install boto                 a   33.67 MB            
01c2b8286373        About a minute ago   /bin/sh -c apt-get update     && apt-get -y -   194.1 MB            
8f40e374788f        14 minutes ago       /bin/sh -c echo "deb-src http://ppa.launchpad   2.027 kB            
768b0264efbe        14 minutes ago       /bin/sh -c echo "deb http://ppa.launchpad.net   1.959 kB            
fa53fd5b228f        14 minutes ago       /bin/sh -c #(nop) MAINTAINER Larry Liang <lar   0 B                 
90d5884b1ee0        3 weeks ago          /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B                 
<missing>           3 weeks ago          /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB            
<missing>           3 weeks ago          /bin/sh -c rm -rf /var/lib/apt/lists/*          0 B                 
<missing>           3 weeks ago          /bin/sh -c set -xe   && echo '#!/bin/sh' > /u   194.5 kB            
<missing>           3 weeks ago          /bin/sh -c #(nop) ADD file:b64f702c5b33d12426   187.8 MB            
```

**Comment by hebbo** [comment]
Definitely an improvement.

Worth bring the extra instruction in I guess.

Thanks for looking at it.

**Pull request merged**
